version: "3.9"  # optional since v1.27.0
services:
  get-buy-price:
    build: ./getBuyPrice
    ports:
      - "49160:8080"
  get-sell-price:
    build: ./getSellPrice
    ports:
      - "49161:8080"
  scheduler:
    build: ./scheduler
    ports:
      - "49162:3000"
    depends_on:
      - influxdb
  wallet:
    build: ./wallet
    ports:
      - "49163:8080"
    depends_on:
      - mongo
  simple-analyzer:
    build: ./simple-analyzer
    ports:
      - "49164:8080"
    depends_on:
      - influxdb
  position-tracking:
    build: ./position-tracking
    ports:
      - "49165:8080"
    depends_on:
      - mongo
  amazon-transaction-post:
    build: ./amazon-transaction-post
    ports:
      - "49166:8080"
      - "443:443"
  influxdb:
    image: "influxdb"
    ports:
      - "8086:8086"
    volumes:
      - "./app:/usr/src/app/app"
  mongo:
    image: "mongo"
    environment:
      MONGO_INITDB_DATABASE: wallet
    ports:
      - "27017:27017"
    volumes:
      - "./app:/usr/src/app/mongo"
      - "./app/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro"
  mongo-express:
    image: "mongo-express"
    ports:
      - "49199:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongo"
    volumes:
      - "./app:/usr/src/app/mongo"
