version: "3.9"  # optional since v1.27.0
services:
  get-buy-price:
    build: ./getBuyPrice
    ports:
      - "49160:8080"
  get-sell-price:
    build: ./getSellPrice
    ports:
      - "49161:8080"
  scheduler:
    build: ./scheduler
    ports:
      - "49162:3000"
    depends_on:
      - influxdb
  wallet:
    build: ./wallet
    ports:
      - "49163:8080"
    depends_on:
      - mysql
  influxdb:
    image: "influxdb"
    ports:
      - "8086:8086"
    volumes:
      - "./app:/usr/src/app/app"
  mysql:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: coinbase_wallet
    volumes:
      - "./app:/usr/src/app/mysql"
      - "./app:/docker-entrypoint-initdb.d"
    healthcheck:
      test: ["CMD", "mysql" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
